# Generated by Django 5.1.6 on 2025-03-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products'),
        ),
    ]
