# Generated by Django 6.0 on 2026-01-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0002_alter_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="pic",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="brands"
            ),
        ),
    ]
