# Generated by Django 6.0 on 2026-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0003_brand_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(max_length=35)),
                ("adressline1", models.CharField(max_length=50)),
                ("adressline2", models.CharField(max_length=50)),
                ("adressline3", models.CharField(max_length=50)),
                ("pin", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                (
                    "pic",
                    models.ImageField(
                        blank=True, default=None, null=True, upload_to="buyers"
                    ),
                ),
            ],
        ),
    ]
