# Generated by Django 6.0 on 2026-01-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_buyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="username",
            field=models.CharField(default="", max_length=30),
        ),
    ]
