# Generated by Django 6.0 on 2026-01-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_buyer_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="adressline1",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="adressline2",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="adressline3",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="city",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pic",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="buyers"
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pin",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="state",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
