# Generated by Django 6.0 on 2026-01-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_alter_buyer_adressline1_alter_buyer_adressline2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="adressline1",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="adressline2",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="adressline3",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="city",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pin",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="state",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
