# Generated by Django 6.0 on 2026-01-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_alter_buyer_adressline1_alter_buyer_adressline2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyer",
            name="adressline1",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="adressline2",
        ),
        migrations.RemoveField(
            model_name="buyer",
            name="adressline3",
        ),
        migrations.AddField(
            model_name="buyer",
            name="addressline1",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="buyer",
            name="addressline2",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="buyer",
            name="addressline3",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="city",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="pin",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="state",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
    ]
