# Generated by Django 6.0 on 2026-01-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0012_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="otp",
            field=models.IntegerField(default=-12332222),
        ),
    ]
