# Generated by Django 6.0 on 2026-01-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0013_buyer_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="rppid",
            field=models.CharField(default="", max_length=100),
        ),
    ]
